spring:
  datasource:
    # yml填写url连接串， 无需将&符号进行转义
    url: jdbc:mysql://127.0.0.1:3306/spider_test?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '000000'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
      pool-name: HikariCP


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl